# Setup
title:               Daniel's Page
tagline:             ''
description:         'My personal page. Based on the Jekyll Lanyon theme (by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>)'
url:                 'https://dm6801.github.io'
baseurl:             ''
paginate:            5
permalink:           ''

# About/contact
author:
  name:              Daniel Malets
  url:               https://www.linkedin.com/in/daniel-malets/
  email:             #

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
